@BackgroundApi_HostAddress = http://localhost:5178
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

### Health check
GET {{BackgroundApi_HostAddress}}/api/health

### Create Order
POST {{BackgroundApi_HostAddress}}/api/orders
Content-Type: application/json
Authorization: {{Token}}

5


### Get Order
GET {{BackgroundApi_HostAddress}}/api/orders/100

### Get inventory
GET {{BackgroundApi_HostAddress}}/api/inventory/100
Authorization: {{Token}}